name: Terraform Apply
description: Apply a Terraform plan
inputs:
  path:
    description: The source plan or directory
    required: false
  decrypt:
    description: Decrypt the plan
    required: false
runs:
  using: node12
  main: dist/index.js
